"""added mime_type to file table

Revision ID: 98068e04c847
Revises: 997c3b74ff50
Create Date: 2026-02-17 18:35:56.785314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98068e04c847'
down_revision: Union[str, Sequence[str], None] = '997c3b74ff50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files_table', sa.Column('mime_type', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files_table', 'mime_type')
    # ### end Alembic commands ###
