"""added username to user table

Revision ID: 997c3b74ff50
Revises: 6f8e672f06b7
Create Date: 2026-02-12 12:30:12.852060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997c3b74ff50'
down_revision: Union[str, Sequence[str], None] = '6f8e672f06b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_table_owner_id_fkey'), 'files_table', type_='foreignkey')
    op.create_foreign_key(None, 'files_table', 'users_table', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('users_table', sa.Column('username', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'username')
    op.drop_constraint(None, 'files_table', type_='foreignkey')
    op.create_foreign_key(op.f('files_table_owner_id_fkey'), 'files_table', 'users_table', ['owner_id'], ['id'])
    # ### end Alembic commands ###
