"""delted b2 file id line

Revision ID: d50411426696
Revises: d5ff697c713a
Create Date: 2026-02-20 18:47:22.599735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50411426696'
down_revision: Union[str, Sequence[str], None] = 'd5ff697c713a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_table_b2_file_id_key'), 'files_table', type_='unique')
    op.drop_column('files_table', 'b2_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files_table', sa.Column('b2_file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('files_table_b2_file_id_key'), 'files_table', ['b2_file_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
