"""initial schema

Revision ID: db95913cb32b
Revises: 
Create Date: 2026-02-19 19:32:35.084126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db95913cb32b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_table_email'), 'users_table', ['email'], unique=True)
    op.alter_column('file_permission_table', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'file_permission_table', 'users_table', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('file_shares_table', 'shared_by',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'file_shares_table', 'users_table', ['shared_by'], ['id'], ondelete='CASCADE')
    op.alter_column('files_table', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'files_table', 'users_table', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files_table', type_='foreignkey')
    op.alter_column('files_table', 'owner_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'file_shares_table', type_='foreignkey')
    op.alter_column('file_shares_table', 'shared_by',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'file_permission_table', type_='foreignkey')
    op.alter_column('file_permission_table', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_table_email'), table_name='users_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
