"""added granted by to FilePermisionTable

Revision ID: efd421807484
Revises: f3afd19ea687
Create Date: 2026-03-04 14:32:53.894502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd421807484'
down_revision: Union[str, Sequence[str], None] = 'f3afd19ea687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_permission_table', sa.Column('granted_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'file_permission_table', 'users_table', ['granted_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_permission_table', type_='foreignkey')
    op.drop_column('file_permission_table', 'granted_by')
    # ### end Alembic commands ###
